name: deploy Eapp-to-tomcat
on:
  push:
    branches: [ "feature" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup JDK 17
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: build with maven
        run: mvn -b package --file pom.xml
      - name: deploy eapp to tomcat
        env:
          tomcatuser: ${{secret.serverusername}}
          tomcatpwd: ${{secret.serverpassword}}
        run: curl -v -u $tomcatuser:$tomcatpassword -T 
          
